INSERT INTO PROVINCE (NAME, COUNTRY) VALUES ("CIUDAD AUTONOMA DE BUENOS AIRES","ARGENTINA");
INSERT INTO PROVINCE (NAME, COUNTRY) VALUES ("PROVINCIA DE BUENOS AIRES","ARGENTINA");
INSERT INTO PROVINCE (NAME, COUNTRY) VALUES ("CORDOBA","ARGENTINA");
INSERT INTO CITY (NAME, PROVINCE_ID) VALUES ("BUENOS AIRES",1);
INSERT INTO CITY (NAME, PROVINCE_ID) VALUES ("TIGRE",2);
INSERT INTO CITY (NAME, PROVINCE_ID) VALUES ("SAN ISIDRO",2);
INSERT INTO NEIGHBORHOOD  (NAME, CITY_ID) VALUES ("BOEDO",1);
INSERT INTO NEIGHBORHOOD  (NAME, CITY_ID) VALUES ("ALMAGRO",1);
INSERT INTO NEIGHBORHOOD  (NAME, CITY_ID) VALUES ("SAN ISIDRO",2);
INSERT INTO NEIGHBORHOOD  (NAME, CITY_ID) VALUES ("ACASSUSSO",2);

INSERT INTO BUILDING (NAME, COUNTRY) VALUES ("CIUDAD AUTONOMA DE BUENOS AIRES","ARGENTINA")

SELECT * FROM PROVINCE
SELECT * FROM city
SELECT * FROM NEIGHBORHOOD